### ISSUE TITLE
On calculation of various quantities

### ISSUE THREAD

**Issue by juanmed** [yorgoon/minimum-snap-geometric-control#1]
Hello!

First of all thanks for sharing your results and code. I am trying to implement a geometric controller for a quadcopter using a minimum-snap trajectory, just like you already did. I was wondering if I could ask some question on several calculations you did. Maybe all of them could be answered if you are kind to provide me some reference papers/documents I can then search for. I already looked for answer in the reference your provide in the README.md but these don't seem to be in those papers. 

a. Desired angular velocity and acceleration calculation. In control_sw2.m [lines 70](https://github.com/yorgoon/minimum-snap-geometric-control/blob/25b4aa13d1e740e96a5cab9a624b919d158dc2aa/control_sw2.m#L70) - [84](https://github.com/yorgoon/minimum-snap-geometric-control/blob/25b4aa13d1e740e96a5cab9a624b919d158dc2aa/control_sw2.m#L84), the desired angular velocity is calculated. Could you please explain how did you come up to this approach? 

b. Desired thrust derivative. I have reviewed several papers and never saw the use of the desired thrust derivate and the acceleration error for feedback control, as you did in [Line 34](https://github.com/yorgoon/minimum-snap-geometric-control/blob/25b4aa13d1e740e96a5cab9a624b919d158dc2aa/control_sw2.m#L34) . This seems clever and maximizes the use of the info from the minimum snap trajectory. Could you please let me know any references I can read more about this?

c. The part I could not really understand well is the desired angular acceleration calculation. More specifically deriving the 2nd derivative of the desired orientation. I am still having issues calculating the first derivate from the commanded orientation. Could you please provide me some references to understand this section?

d. On calculation of the orientation error. I understand there are two forms of calculating the error as you did in [Line 56](https://github.com/yorgoon/minimum-snap-geometric-control/blob/25b4aa13d1e740e96a5cab9a624b919d158dc2aa/control_sw2.m#L56) and [57](https://github.com/yorgoon/minimum-snap-geometric-control/blob/25b4aa13d1e740e96a5cab9a624b919d158dc2aa/control_sw2.m#L57). However, what is it that you are doing from [line 58](https://github.com/yorgoon/minimum-snap-geometric-control/blob/25b4aa13d1e740e96a5cab9a624b919d158dc2aa/control_sw2.m#L58) to 66? 

e. I learned after much fighting that the orientation controller should be much faster than the position controller. In other words, the position controller requires the desired orientation to converge first, and then it is able to converge the position error to zero. However, you don't seem to be doing this, and both position and orientation control work at the same speed. Is this true? 

As general comments, for the position controller, my results are good, and orientation control using Euler angles is fine. However I want to move away from Euler angles, and I am having issues implementing the orientation control in SO(3). Your comments will be greatly appreciated! And sorry for the long post :/

- Juan

**Comment by yorgoon** [comment]
I am so sorry that I didn't realize someone "actually" looked at and try to use my code until now. It's been a long time since I finished this project, but I will try to answer your questions as soon as possible even if you either figured it out or not working on this subject anymore since it's been almost 6 months ago... in the hope of helping others as well.

**Answer a.**
I will briefly answer the first question and will come back soon on the rest of the questions.
a. To get the desired angular velocity with respect to the inertial frame expressed in the body frame, simply write as <a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{\omega}^b_d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{\omega}^b_d" title="\boldsymbol{\omega}^b_d" /></a> we need the desired rotation of the body frame to the inertial frame, <a href="https://www.codecogs.com/eqnedit.php?latex=R_d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?R_d" title="R_d" /></a>. 

<a href="https://www.codecogs.com/eqnedit.php?latex=R_d=[\boldsymbol{x}_d^b,&space;\boldsymbol{y}_d^b,&space;\boldsymbol{z}_d^b]^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?R_d=[\boldsymbol{x}_d^b,&space;\boldsymbol{y}_d^b,&space;\boldsymbol{z}_d^b]^T" title="R_d=[\boldsymbol{x}_d^b, \boldsymbol{y}_d^b, \boldsymbol{z}_d^b]^T" /></a>
1. The z component (3rd column) can be computed knowing the fact that is always aligned with the desired thrust, <a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{F}_d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{F}_d" title="\boldsymbol{F}_d" /></a> (by physical constraint on the quadrotor). 
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{z}^b_d=\frac{\boldsymbol{F}_d}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{z}^b_d=\frac{\boldsymbol{F}_d}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}" title="\boldsymbol{z}^b_d=\frac{\boldsymbol{F}_d}{\left \| \boldsymbol{F}_d \right \|}" /></a>

2. The y component is computed based on the fact that the y component is normal to the x-axis of the intermediate frame (after rotating about z-axis in Z-X-Y Euler angle sequence) and the z component we've got above. 
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{x}_{c,des}=[cos(\psi),&space;sin(\psi),&space;0]^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{x}_{c,des}=[cos(\psi),&space;sin(\psi),&space;0]^T" title="\boldsymbol{x}_{c,des}=[cos(\psi), sin(\psi), 0]^T" /></a> where <a href="https://www.codecogs.com/eqnedit.php?latex=\psi" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\psi" title="\psi" /></a> is the desired yaw angle.
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{y}_d^b=\frac{\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}}{\left&space;\|&space;\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{y}_d^b=\frac{\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}}{\left&space;\|&space;\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}&space;\right&space;\|}" title="\boldsymbol{y}_d^b=\frac{\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}}{\left \| \boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des} \right \|}" /></a>
3. Now we have y and z component, we can get x component by cross(y,z). 
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{x}_d^b=\frac{\boldsymbol{y}_d^b\times\boldsymbol{z}_d^b}{\left&space;\|&space;\boldsymbol{y}_d^b\times\boldsymbol{z}_d^b&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{x}_d^b=\frac{\boldsymbol{y}_d^b\times\boldsymbol{z}_d^b}{\left&space;\|&space;\boldsymbol{y}_d^b\times\boldsymbol{z}_d^b&space;\right&space;\|}" title="\boldsymbol{x}_d^b=\frac{\boldsymbol{y}_d^b\times\boldsymbol{z}_d^b}{\left \| \boldsymbol{y}_d^b\times\boldsymbol{z}_d^b \right \|}" /></a>
Then one can compute time derivative of `Rd`, called `Rd_dot`. 
Finally, <a href="https://www.codecogs.com/eqnedit.php?latex=\widehat{\boldsymbol{\omega}^b_d}=R_d^T\dot{R_d}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\widehat{\boldsymbol{\omega}^b_d}=R_d^T\dot{R_d}" title="\widehat{\boldsymbol{\omega}^b_d}=R_d^T\dot{R_d}" /></a>

**Comment by yorgoon** [comment]
**Answer b.**
Again we want the desired angular velocity of the body frame with respect to the inertial frame "expressed" in the body frame.
<a href="https://www.codecogs.com/eqnedit.php?latex=\widehat{\boldsymbol{\omega}^b_d}=R_d^T\dot{R_d}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\widehat{\boldsymbol{\omega}^b_d}=R_d^T\dot{R_d}" title="\widehat{\boldsymbol{\omega}^b_d}=R_d^T\dot{R_d}" /></a>
where 
<a href="https://www.codecogs.com/eqnedit.php?latex=R_d=[\boldsymbol{x_d^b},&space;\boldsymbol{y_d^b},&space;\boldsymbol{z_d^b}]^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?R_d=[\boldsymbol{x_d^b},&space;\boldsymbol{y_d^b},&space;\boldsymbol{z_d^b}]^T" title="R_d=[\boldsymbol{x_d^b}, \boldsymbol{y_d^b}, \boldsymbol{z_d^b}]^T" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\dot{R_d}=[\dot{\boldsymbol{x_d^b}},&space;\dot{\boldsymbol{y_d^b}},&space;\dot{\boldsymbol{z_d^b}}]^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{R_d}=[\dot{\boldsymbol{x_d^b}},&space;\dot{\boldsymbol{y_d^b}},&space;\dot{\boldsymbol{z_d^b}}]^T" title="\dot{R_d}=[\dot{\boldsymbol{x_d^b}}, \dot{\boldsymbol{y_d^b}}, \dot{\boldsymbol{z_d^b}}]^T" /></a>
Each column represents the unit vector of the major axis of the body frame with respect to the inertial frame. Again, the desired z-axis of the body frame always aligned with the direction of the desired thrust. We can derive the deisred z-axis in terms of the desired thrust.
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{z}^b_d=\frac{\boldsymbol{F}_d}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{z}^b_d=\frac{\boldsymbol{F}_d}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}" title="\boldsymbol{z}^b_d=\frac{\boldsymbol{F}_d}{\left \| \boldsymbol{F}_d \right \|}" /></a>
Now it is clear that we need the time derivative of the desired thrust, <a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{\dot{F_d}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{\dot{F_d}}" title="\boldsymbol{\dot{F_d}}" /></a> or `Fd_dot` to get the time derivative of the desired z-axis.

Note*
Hat operator, ^ that is applied to <a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{\omega}_d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{\omega}_d" title="\boldsymbol{\omega}_d" /></a> is a skew-symmetric matrix representation of a cross product.
ex
<a href="https://www.codecogs.com/eqnedit.php?latex=\widehat{\bold{a}}=\begin{bmatrix}&space;0&space;&&space;-a_3&space;&a_2&space;\\&space;a_3&0&space;&&space;-a_1\\&space;-a_2&&space;a_1&space;&0&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\widehat{\bold{a}}=\begin{bmatrix}&space;0&space;&&space;-a_3&space;&a_2&space;\\&space;a_3&0&space;&&space;-a_1\\&space;-a_2&&space;a_1&space;&0&space;\end{bmatrix}" title="\widehat{\bold{a}}=\begin{bmatrix} 0 & -a_3 &a_2 \\ a_3&0 & -a_1\\ -a_2& a_1 &0 \end{bmatrix}" /></a>

**Comment by yorgoon** [comment]
**Answer c.**
First derivatives
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{F}_d&space;=&space;-K_pe_p&space;-K_ve_v&space;&plus;&space;[0,&space;0,&space;mg]^T&space;&plus;&space;ma_d&space;\\&space;\frac{d}{dt}\boldsymbol{F}_d&space;=&space;\dot{\boldsymbol{F}_d}=-K_pe_v&space;-K_ve_a&space;&plus;&space;mj_d&space;\\&space;\frac{d}{dt}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|=\frac{\boldsymbol{F}_d\cdot&space;\dot{\boldsymbol{F}_d}}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}&space;\\&space;\frac{d}{dt}\boldsymbol{z}_d^b=\dot{\boldsymbol{z}_d^b}=\frac{\dot{\boldsymbol{F}_d}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|-\boldsymbol{F}_d\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{F}_d&space;=&space;-K_pe_p&space;-K_ve_v&space;&plus;&space;[0,&space;0,&space;mg]^T&space;&plus;&space;ma_d&space;\\&space;\frac{d}{dt}\boldsymbol{F}_d&space;=&space;\dot{\boldsymbol{F}_d}=-K_pe_v&space;-K_ve_a&space;&plus;&space;mj_d&space;\\&space;\frac{d}{dt}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|=\frac{\boldsymbol{F}_d\cdot&space;\dot{\boldsymbol{F}_d}}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}&space;\\&space;\frac{d}{dt}\boldsymbol{z}_d^b=\dot{\boldsymbol{z}_d^b}=\frac{\dot{\boldsymbol{F}_d}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|-\boldsymbol{F}_d\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^2}" title="\boldsymbol{F}_d = -K_pe_p -K_ve_v + [0, 0, mg]^T + ma_d \\ \frac{d}{dt}\boldsymbol{F}_d = \dot{\boldsymbol{F}_d}=-K_pe_v -K_ve_a + mj_d \\ \frac{d}{dt}\left \| \boldsymbol{F}_d \right \|=\frac{\boldsymbol{F}_d\cdot \dot{\boldsymbol{F}_d}}{\left \| \boldsymbol{F}_d \right \|} \\ \frac{d}{dt}\boldsymbol{z}_d^b=\dot{\boldsymbol{z}_d^b}=\frac{\dot{\boldsymbol{F}_d}\left \| \boldsymbol{F}_d \right \|-\boldsymbol{F}_d\dot{\left \| \boldsymbol{F}_d \right \|}}{\left \| \boldsymbol{F}_d \right \|^2}" /></a>

Let
<a href="https://www.codecogs.com/eqnedit.php?latex=\boldsymbol{y}_d^b=\frac{\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}}{\left&space;\|&space;\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}&space;\right&space;\|}=\frac{\bold{a}}{\left&space;\|&space;\bold{a}&space;\right&space;\|}\\" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\boldsymbol{y}_d^b=\frac{\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}}{\left&space;\|&space;\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}&space;\right&space;\|}=\frac{\bold{a}}{\left&space;\|&space;\bold{a}&space;\right&space;\|}\\" title="\boldsymbol{y}_d^b=\frac{\boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des}}{\left \| \boldsymbol{z}_d^b\times\boldsymbol{x}_{c,des} \right \|}=\frac{\bold{a}}{\left \| \bold{a} \right \|}\\" /></a>
Then the time derivative can be expressed as
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{d}{dt}\boldsymbol{y}_d^b=\dot{\boldsymbol{y}_d^b}=\frac{\dot{\bold{a}}\left&space;\|&space;\bold{a}&space;\right&space;\|-\bold{a}\dot{\left&space;\|&space;\bold{a}&space;\right&space;\|}}{\left&space;\|&space;\bold{a}&space;\right&space;\|^2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{d}{dt}\boldsymbol{y}_d^b=\dot{\boldsymbol{y}_d^b}=\frac{\dot{\bold{a}}\left&space;\|&space;\bold{a}&space;\right&space;\|-\bold{a}\dot{\left&space;\|&space;\bold{a}&space;\right&space;\|}}{\left&space;\|&space;\bold{a}&space;\right&space;\|^2}" title="\frac{d}{dt}\boldsymbol{y}_d^b=\dot{\boldsymbol{y}_d^b}=\frac{\dot{\bold{a}}\left \| \bold{a} \right \|-\bold{a}\dot{\left \| \bold{a} \right \|}}{\left \| \bold{a} \right \|^2}" /></a>
where
<a href="https://www.codecogs.com/eqnedit.php?latex=\dot{\bold{a}}=\dot{\boldsymbol{z}_d^b}\times\boldsymbol{x}_{c,des}&plus;\boldsymbol{z}_d^b\times\dot{\boldsymbol{x}_{c,des}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{\bold{a}}=\dot{\boldsymbol{z}_d^b}\times\boldsymbol{x}_{c,des}&plus;\boldsymbol{z}_d^b\times\dot{\boldsymbol{x}_{c,des}}" title="\dot{\bold{a}}=\dot{\boldsymbol{z}_d^b}\times\boldsymbol{x}_{c,des}+\boldsymbol{z}_d^b\times\dot{\boldsymbol{x}_{c,des}}" /></a>
We already have <a href="https://www.codecogs.com/eqnedit.php?latex=\dot{\boldsymbol{z}_d^b}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{\boldsymbol{z}_d^b}" title="\dot{\boldsymbol{z}_d^b}" /></a>.
<a href="https://www.codecogs.com/eqnedit.php?latex=\dot{\boldsymbol{x}}_{c,des}=[-\dot{\psi}sin(\psi),&space;\dot{\psi}cos(\psi),&space;0]^T" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{\boldsymbol{x}}_{c,des}=[-\dot{\psi}sin(\psi),&space;\dot{\psi}cos(\psi),&space;0]^T" title="\dot{\boldsymbol{x}}_{c,des}=[-\dot{\psi}sin(\psi), \dot{\psi}cos(\psi), 0]^T" /></a>
Since <a href="https://www.codecogs.com/eqnedit.php?latex=\dot{\left&space;\|&space;\bold{a}&space;\right&space;\|}=\frac{\bold{a}\cdot\dot{\bold{a}}}{\left&space;\|&space;\bold{a}&space;\right&space;\|}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{\left&space;\|&space;\bold{a}&space;\right&space;\|}=\frac{\bold{a}\cdot\dot{\bold{a}}}{\left&space;\|&space;\bold{a}&space;\right&space;\|}" title="\dot{\left \| \bold{a} \right \|}=\frac{\bold{a}\cdot\dot{\bold{a}}}{\left \| \bold{a} \right \|}" /></a>, we can compute <a href="https://www.codecogs.com/eqnedit.php?latex=\dot{\boldsymbol{y}_d^b}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{\boldsymbol{y}_d^b}" title="\dot{\boldsymbol{y}_d^b}" /></a>.

Using a similar approach, we can compute <a href="https://www.codecogs.com/eqnedit.php?latex=\dot{\boldsymbol{x}_d^b}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\dot{\boldsymbol{x}_d^b}" title="\dot{\boldsymbol{x}_d^b}" /></a>.

**Comment by yorgoon** [comment]
**Answer c. continued**
Second derivatives
As usual, we will start with z component.

<a href="https://www.codecogs.com/eqnedit.php?latex=\ddot{\boldsymbol{z}_d^b}=\frac{\ddot{\boldsymbol{F}_d}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^2-2\boldsymbol{F}_d\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}^2-\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|(2\dot{\boldsymbol{F}_d}\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}&plus;\boldsymbol{F}_d\ddot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|})}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^3}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\ddot{\boldsymbol{z}_d^b}=\frac{\ddot{\boldsymbol{F}_d}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^2-2\boldsymbol{F}_d\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}^2-\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|(2\dot{\boldsymbol{F}_d}\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}&plus;\boldsymbol{F}_d\ddot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|})}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^3}" title="\ddot{\boldsymbol{z}_d^b}=\frac{\ddot{\boldsymbol{F}_d}\left \| \boldsymbol{F}_d \right \|^2-2\boldsymbol{F}_d\dot{\left \| \boldsymbol{F}_d \right \|}^2-\left \| \boldsymbol{F}_d \right \|(2\dot{\boldsymbol{F}_d}\dot{\left \| \boldsymbol{F}_d \right \|}+\boldsymbol{F}_d\ddot{\left \| \boldsymbol{F}_d \right \|})}{\left \| \boldsymbol{F}_d \right \|^3}" /></a>
where the 2nd time derivative of the desired thrust can be expressed in terms of the acceleration error, jerk error, and the desired snap.

<a href="https://www.codecogs.com/eqnedit.php?latex=\ddot{\boldsymbol{F}_d}=-K_pe_a&space;-K_ve_j&space;&plus;&space;ms_d" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\ddot{\boldsymbol{F}_d}=-K_pe_a&space;-K_ve_j&space;&plus;&space;ms_d" title="\ddot{\boldsymbol{F}_d}=-K_pe_a -K_ve_j + ms_d" /></a>

<a href="https://www.codecogs.com/eqnedit.php?latex=\ddot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}=\frac{d^2}{dt^2}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|=\frac{-(\boldsymbol{F}_d\cdot&space;\dot{\boldsymbol{F}_d})^2&plus;\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^2(\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}^2&plus;\boldsymbol{F}_d\cdot&space;\ddot{\boldsymbol{F}_d})}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^3}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\ddot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}=\frac{d^2}{dt^2}\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|=\frac{-(\boldsymbol{F}_d\cdot&space;\dot{\boldsymbol{F}_d})^2&plus;\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^2(\dot{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|}^2&plus;\boldsymbol{F}_d\cdot&space;\ddot{\boldsymbol{F}_d})}{\left&space;\|&space;\boldsymbol{F}_d&space;\right&space;\|^3}" title="\ddot{\left \| \boldsymbol{F}_d \right \|}=\frac{d^2}{dt^2}\left \| \boldsymbol{F}_d \right \|=\frac{-(\boldsymbol{F}_d\cdot \dot{\boldsymbol{F}_d})^2+\left \| \boldsymbol{F}_d \right \|^2(\dot{\left \| \boldsymbol{F}_d \right \|}^2+\boldsymbol{F}_d\cdot \ddot{\boldsymbol{F}_d})}{\left \| \boldsymbol{F}_d \right \|^3}" /></a>

Similarly, by using the 2nd derivative of 2-norm, we can compute <a href="https://www.codecogs.com/eqnedit.php?latex=\ddot{\boldsymbol{y}_d^b}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\ddot{\boldsymbol{y}_d^b}" title="\ddot{\boldsymbol{y}_d^b}" /></a> and <a href="https://www.codecogs.com/eqnedit.php?latex=\ddot{\boldsymbol{x}_d^b}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\ddot{\boldsymbol{x}_d^b}" title="\ddot{\boldsymbol{x}_d^b}" /></a>.

**Comment by yorgoon** [comment]
**Answer d.**
I was experimenting maneuver with high speed that requires yaw more than 90degrees. This was causing some problems with the controller. I disabled it for now. I also made a lot of changes including encapsulating the trajectory optimization using minimum snap. Please fetch this new version.

**Comment by yorgoon** [comment]
**Answer e.**
According to the paper, first, we get to choose the desired magnitude and direction of the total thrust to converge the translational tracking. The chosen control law for this is equation (12). Then the remaining degree of freedom we have to track is the desired heading direction (yaw). This is chosen by the appropriate moment, equation (13). This complete package of control commend is calculated in a single iteration. So to answer, I think translational tracking and orientational tracking is done at the same “speed.”

**Comment by yorgoon** [comment]
**Answer to general comment**
I think the reason of using Euler angles is from the fact that the dynamics of a quadrotor is differentially flat with 3 translations and 1 orientation. So we design the desired translations (xd, yd, zd) and yaw (psi_d) using either minimum snap, or acceleration trajectories.

**Comment by juanmed** [comment]
@yorgoon Wow! Thank you very much for your detailed answer to all my questions, this is really helpful as your code base was when I was learning from it. I will go again through all of these. I am actually trying to implement this controller on a real drone, and tunning the PID gains has been the hardest part so far (lots of propellers broken and quite a few terrible crashes). Thank you very much!

**Comment by yorgoon** [comment]
> @yorgoon Wow! Thank you very much for your detailed answer to all my questions, this is really helpful as your code base was when I was learning from it. I will go again through all of these. I am actually trying to implement this controller on a real drone, and tunning the PID gains has been the hardest part so far (lots of propellers broken and quite a few terrible crashes). Thank you very much!

I am more than pleased to know that. Please let me know if you have further questions.
